packages/create-wmr/tpl/package.json
Without this, the scaffolded template will only work via global `wmr` installations
=> fix(create-wmr): add "wmr" as devdep

types.d.ts
The previous order matched `*.css` declarations for a `styles.module.css` file because it comes first in the types. This meant that all `className={ styles.home }` failed to typecheck, since `styles` was matched as a string.
This change allows `styles.modules.css` to be treated as a `Mapping` type, where as `styles.css` is treated as a `string` when imported.
=> fix(types): swap `declare` order for `*.module.css` files

src/start.js
Moves the logging for server addresses in the listen callback, since we can't always assume that the `listening` event has already been emitted when we're retrieving the addresses.
Closes #202
=> Move server address log in listen callback

README.md
Added individual config functions so that that variant is more visible. Although it's mentioned in the paragraph above the code sample, it's still easy to gloss over.
Also changed the file annotation to `wmr.config.mjs` because ESM inside `.js` only works by default when `"type": "module"` is defined. Since that's not set on the `create-wmr` template, safe to assume `wmr.config.js` + ESM won't work for most out of the box.
=> chore: update readme `wmr.config.js` snippet

src/bundler.js, src/cli.js, src/wmr-middleware.js, types.d.ts
- enabled by default (no change)
- disable via `--no-minify` or `--minify=0` or `--minify=false`
- disable via `config.minify = false`
---
May be good to have this to debug what's going on w/ production. (Not everyone can follow Terser output 😉)
Am roughly doing this to debug what's going on with #213 
***TODO***
* Rename this to `--compress`?
_Would be common term between commands, but `build`'s meaning would be different._
* Hide this from the CLI help text?
_Could still attach it to CLI, but not advertise it in `wmr build -h` output._
* Do we even want this?
_Didn't discuss this with anyone, sorry~!_
=> feat: add `minify` config

package-lock.json, package.json, rollup.config.js, src/bundler.js
There was only `tiny-glob` usage inside `bundler.js` to collect HTML input files (updated) and inside `watch-plugin.js`, which was unused.
No need to bring in the `tiny-glob` dependency chain when just crawling for a single extension.
(~1.5kb => 200b gzip)
=> chore: replace `tiny-glob` with `totalist` for inputs

README.md, packages/create-wmr/src/index.js
Adds support for initializing WMR project with Yarn.
Also now properly catches in the chance the chosen package manager is not installed/accessible.
=> feat: Adding support for yarn in create-wmr

packages/preact-iso/hydrate.d.ts, packages/preact-iso/index.d.ts, packages/preact-iso/lazy.d.ts, packages/preact-iso/package.json, packages/preact-iso/prerender.d.ts, packages/preact-iso/router.d.ts
Adds types to `preact-iso` package. Closes #243 .
Let me know if anything looks incorrect. I've tested locally in a WMR app with the `tsconfig` having `strict` enabled and everything seemed to work correctly.
=> feat: Adding types for preact-iso

packages/create-wmr/src/index.js
Might also make sense to have `preact-iso` auto-import `preact/debug` in development mode?
=> create-wmr should pre-install preact

packages/create-wmr/tpl/tsconfig.json
Enabling `noImplicitAny` or `strict` in a new WMR app with `.tsx` files will present the following error at every usage of JSX: 
```
TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
```
While this won't hinder the app from being built in any way, it is quite distracting in an IDE. This should stop that error from popping up.
=> fix: Adding jsxFactory to create-wmr's tsconfig file

src/bundler.js, src/plugins/node-builtins-plugin.js, test/fixtures.test.js, test/fixtures/node-builtins/http.js
First pass at adding a helpful error message when attempting to use Node built-ins.
Let me know if any changes need making!
=> WMR-229 node builtins

src/plugins/node-builtins-plugin.js, test/fixtures.test.js, types.d.ts
This essentially does what #245 did but for folks who aren't using `create-wmr`.
Fixes #258.
=> Hoist JSX namespace to be global by default

packages/@wmr-plugins_nomodule/README.md
Very easy fix, it's fine if one of the contributor make this fix themselves directly but just wanted to make someone aware of the spelling mistake.
Thank for the great work you are all doing. This project is very exciting.
=> Fix typo (was missing a `'`)

packages/preact-iso/router.d.ts, packages/preact-iso/router.js
Addresses & closes #269 
Adds a simple alias `useLocation()` for `useLoc()`. React-router, Reach, and Wouter all use `useLocation()` so I imagine this is more comfortable for a pretty large group of people.
=> preact-iso: Adding "useLocation" alias for "useLoc"

README.md
Created in regards to #282. For those that set up WMR manually a note about the alias that comes with the template could be helpful.
Let me know if the verbiage should be altered or anything. The first sentence is swiped from the Preact site.
=> docs: Adding preact/compat note to the README

src/lib/prerender.js
At times the `dist/index.html` file would have a `<link rel="undefined" href="undefined">` added just before the end of `head`. Filtering out the links with missing values solves it. 👍
=> (fix) Filter the link tags based on rel and href

src/cli.js
`--no-compress` produces `{ compress: false }` from Sade, but we were only testing for `compress !== 'false'`.
=> Fix --no-compress option

src/plugins/wmr/styles-plugin.js
Enjoying playing around with with this, thanks!
Ran into an issue with css module class names that contain multiple dashes (e.g. BEM).
This is only half a fix, as there’s still the possibility of an overlap (‘foo-bar’ and ‘foo--bar’), but this is less likely the multiple dash case. Short of replacing -- with something even less likely to occur, I wasn’t sure of a better solution!
=> Fix multiple dashes in css modules

src/serve.js
For some reason I didn't catch this - `wmr serve` doesn't use `server.js` to instantiate its web server (it probably should?), which meant it was never registering middlewares.
=> Bugfix: `wmr serve` should support middleware option

src/server.js
Our server is 99% intended for development use, where there is little reason to have keep-alive connections expire.
=> Increase HTTP/1 Keep-Alive timeout from 5s to 60s

README.md
I also updated the service worker recipe to include a mention of a manifest file in case people are confused as to why their PWA isn't working with WMR.
=> Add service worker to recipes

src/plugins/optimize-graph-plugin.js
This fixes #327 
The previous regex was too greedy and would break if it came across a function with multiple arguments where the first was a string and the last was _not_ a string.
[Here's](https://regexr.com/5lpav) what the previous regex was doing, occasionally causing paths not to be picked up.
And [here's](https://regexr.com/5lpb8) the proposed version, which makes sure it can't accidentally go past the end of a string.
I wasn't sure how best to add tests for this though, happy to try and add something based off the repro case I found in #327
=> Fix brittle regex in optimize-graph-plugin

packages/preact-iso/package.json
Using `preact-iso` outside of WMR will lead to issues when `preact` and `preact-render-to-string` don't get auto-magically imported. Adding them as peerDeps will at least throw a warning to the user that they're needed.
As far as I know, the `type: module` should be needed when using this from Node, else Node will assume CJS.
=> Preact-ISO fix: Adding peerDeps & correcting module type

src/plugins/url-plugin.js
I fixed a bug that only affects dev mode in Windows devices, where assets were pointing to bad urls cause of Windows backslash path separator.
**What caused it?**
The cause was that url paths to assets weren't being normalized when building inline modules. Generating modules like this:
Pointing to paths that don't exist:
=> Fix assets bad url on dev mode Windows

package.json, packages/preact-iso/package.json, src/wmr-middleware.js
I fixed a bug that only affects windows devices, where some files were triggering HMR but sending old changes to the browser.
**What caused it?**
The cause was that .css and .css.js files cache keys were not being normalized when saved, but only when being removed from **WRITE_CACHE**. Making the server always return old cached CSS files cause of the "\\" Windows path separator.
**How did I solve it?**
I created the **getCacheKeyById** function at the top of **wmr-middleware.js** file and used it on js, css and cssModule transforms functions for cacheKey normalization.
I also added **cross-env** to the dev script for Windows compatibility.
[This](https://github.com/preactjs/wmr/issues/246#issuecomment-748804874) issue helped me to find out the problem.
=> Fix HMR not working with CSS on Windows

package-lock.json, package.json, src/bundler.js, test/fixtures/dynamic-import/index.html, test/fixtures/dynamic-import/index.js, test/fixtures/dynamic-import/pages/one.js, test/fixtures/dynamic-import/pages/two.js, test/production.test.js
This makes it possible to use variables in dynamic imports in production, not just in development:
```js
const pages = await ['one', 'two'].map(page => import(`./pages/${page}.js`))
```
FWIW I'm not super thrilled with the performance of this off-the-shelf plugin - it pulls in a bunch of new dependencies for scanning the disk via path globs, but our use-case doesn't really necessitate them. A simplified version could be written on top of `totalist`, which we're already using. It also unconditionally invokes `this.parse()` on every module, which could be avoided by ignoring modules that don't match a basic pattern like `\bimport\s*(\/\*[\s\S]*?\*\/)\s*\(`. If performance tanks, this could also just be done by wrapping the rollup plugin:
```js
import _dynamicImportVars from …
```
=> Variable dynamic import prod

package-lock.json, package.json, src/bundler.js
Closes the Rollup bundle before passing the output, no internal WMR plugins uses the `closeBundle` hook yet, so this is mainly oriented towards user adding their own plugins.
=> feat: close Rollup bundle before passing output

.github/workflows/compressed-size.yml, .github/workflows/main.yml
The Compressed-Size workflow had an incorrect pattern that needed to be fixed. 
This also limits the WMR build/lint/test & Compressed-Size workflows to only run when appropriate. As of now, they only are concerned about content within `packages/wmr` so the workflows paths have been updated to match. They won't run when `preact-iso` or `create-wmr` have changes.
=> ci: Revising workflow files

packages/preact-iso/package.json, yarn.lock
Jest [supports Node's native ESM](https://jestjs.io/docs/en/ecmascript-modules) now, and it seems to work nicely! A quick test shows it's around 30% faster, which is pretty nice.
=> Router params: use Jest's ESM support

.changeset/orange-eels-smoke.md, .changeset/tall-apes-agree.md, packages/create-wmr/tpl/package.json, packages/create-wmr/tpl/public/header.js, packages/preact-iso/index.js, packages/preact-iso/router.d.ts, packages/preact-iso/router.js, packages/wmr/demo/public/header.tsx, packages/wmr/demo/public/lib/loc.js
We could also opt to start bundling `preact-iso` if this is wanted for this major?
=> Remove deprecated useLoc

.changeset/silly-shrimps-build.md, packages/preact-iso/router.js, packages/wmr/demo/public/lib/loc.js
The router flicker fix from #358 and #337 didn't account for hydration, and was resulting in `lazy()` components being deopted out of hydration and their contents duplicated. This fixes that issue by only applying the VNode reorder workaround to client-side route transitions.
=> Bugfix:router hydration duplication

.changeset/smart-ways-rule.md, packages/preact-iso/hydrate.d.ts
This fixes `parent` argument definition to be compatible with [`preact.render`](https://github.com/preactjs/preact/blob/10.5.12/src/index.d.ts#L226) and [`preact.hydrate`](https://github.com/preactjs/preact/blob/10.5.12/src/index.d.ts#L231) which are called under the hood:
Use case:
```jsx
// Argument of type 'HTMLElement' is not assignable to parameter of type 'VNode<{}>'.
hydrate(<App />, document.body)
```
=> preact-iso: Fix hydrate parent definition

.changeset/grumpy-pens-decide.md, packages/create-wmr/src/index.js
After blowing up another project with an accidental `npm init`, I remembered this bug (?). Not sure if we really want this behavior or not, so I thought I'd bring this back up. 
The implementation here is pretty much swiped from `preact-cli`. Not a huge fan of another flag, but just an idea.
=> refactor: create-wmr checks dir before installing

.changeset/plenty-baboons-sort.md, packages/create-wmr/src/index.js
If the directory does not exist, `fs.stat()` will throw and currently that's uncaught.
Not sure how I missed this
=> fix: Uncaught fs.stat() throw

.changeset/smooth-needles-poke.md, packages/create-wmr/src/index.js, packages/create-wmr/tpl/package.json
This isn't necessarily needed, but seeing as how [`preact` is installed by `create-wmr`](https://github.com/preactjs/wmr/blob/247c7b291fbb4b684d6b3c566135ada5513ed9a3/packages/create-wmr/src/index.js#L41), I think it should probably be listed as a dependency? Especially if any inference like mentioned in https://github.com/preactjs/wmr/pull/322#issuecomment-770534992 is later added.
=> refactor: Adding 'preact' as a dependency to create-wmr template

.changeset/strange-beers-play.md, .gitignore, packages/wmr/package.json, packages/wmr/src/plugins/npm-plugin/resolve.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/exports/node_modules/test/browser.mjs, packages/wmr/test/fixtures/exports/node_modules/test/node.mjs, packages/wmr/test/fixtures/exports/node_modules/test/package.json, packages/wmr/test/fixtures/exports/public/index.html, packages/wmr/test/fixtures/exports/public/index.js, yarn.lock
=> (wmr) - resolve default over node

.changeset/hot-squids-learn.md, packages/wmr/src/plugins/bundle-plugin.js
JavaScript imports can use either single or double quotes:
```js
import 'bundle:./file';
import "bundle:./file";
```
Currently, when using double quotes, the import fail because it's being translated to:
```js
import "data:text/javascript,export default"./file""
```
With this PR, it'll be translated to:
```js
import "data:text/javascript,export default%22./file%22"
```
=> (wmr) Fix double quotes imports with bundle-plugin

.github/workflows/compressed-size.yml, .github/workflows/main.yml
This should fix the issue of actions being required on PRs but never running due to the paths
Seems to be a decent action, does what it says on the tin: https://github.com/dorny/paths-filter
=> ci: Fixing actions on PRs with better pathing tool

packages/wmr/demo/public/index.tsx, packages/wmr/demo/public/lib/hydrate.js
resolves https://github.com/preactjs/wmr/issues/401
=> fix example, use preact-iso/hydrate

.changeset/wise-hats-marry.md, packages/preact-iso/router.d.ts, packages/preact-iso/router.js
Apologies in advance if this gets a bit long winded. 
This PR adds a simple `Route` component that matches the one used in `preact-router`. The problem that it looks to solve is around the typings. The current support for using any component as a route brings on a few problems, namely, those route props have to be [added to every single component globally](https://github.com/preactjs/wmr/blob/91bc136e5c4a47c3ee3613e4d65183f4160ebe8e/packages/preact-iso/router.d.ts#L22-L27) and for typed components that expect route parameters, this method does not work. 
For example,
```
const Example = (props: { id: number }) => <p>{props.id}</p>;
function App() {
return (
<LocationProvider>
<Router>
<Example path="/example/:id" /> <--- Bad, has error
<Route path="/example/:id" component={Example} /> …
```
=> Preact-ISO: Adding TS-approved Route component

.changeset/sharp-cats-relate.md, packages/preact-iso/router.js
At this moment routers' reducer dispatcher behaves as follows:
- User action (MouseEvent):
window location is updated via `history.pushState`
- User navigation via back/ forward (PopStateEvent):
window location is left intact, as it's change is handled by browser
- Manual route change via `useLocation().route(path)`
window location is left intact
This PR
- Fixes last case so `history.pushState` is used to add new entry to browsers history and in effect location changes.
- Moves `push`  from dispatcher argument to function code block, As reducer dispatchers consume only two arguments. it gave false indication that the argument may be chosen somehow.
- Makes it clear that in reality there is no way to set `push` to false and in effect use `history.replaceState`
=> (preact-iso): Router: Fix change location after useLocation().route()

.changeset/cyan-badgers-grab.md, packages/preact-iso/router.js, packages/preact-iso/test/match.test.js, packages/wmr/demo/public/lib/loc.js
=> (preact-iso) - trim leading and trailing slash

.changeset/gorgeous-pants-brush.md, packages/wmr/package.json, packages/wmr/src/lib/normalize-options.js, packages/wmr/src/lib/output-utils.js, packages/wmr/src/lib/rollup-plugin-container.js, packages/wmr/src/plugins/aliases-plugin.js, packages/wmr/src/plugins/bundle-plugin.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/test-helpers.js, yarn.lock
Add colored namespaces to debug output
=> debug-pretty

.changeset/thin-coins-peel.md, packages/wmr/src/lib/net-utils.js, packages/wmr/src/lib/output-utils.js, packages/wmr/src/serve.js, packages/wmr/src/start.js, packages/wmr/test/boot.test.js, packages/wmr/test/test-helpers.js
This PR adds a redesigned startup screen. It tries to fit with the logo we'll share soon.
Before:
After:
=> Use astronaut design for startup screen

.changeset/silver-steaks-sniff.md, packages/wmr/src/lib/output-utils.js
I messed up the last commit in #450 when applying the review comments.
Before:
After:
=> Align astronaut emoji with addresses in cli

.changeset/warm-jars-fetch.md, packages/wmr/src/lib/net-utils.js, packages/wmr/src/start.js
Before this PR we'd silently choose a different port, even if the user explicitely requested one via `--port` or `process.env.PORT`
=> Throw if the user requests a port and it's already taken

.changeset/clean-ads-obey.md, packages/wmr/package.json, packages/wmr/src/cli.js, yarn.lock
=> Always print stack traces on exceptions

.changeset/five-hornets-admire.md, .github/workflows/main.yml, packages/wmr/src/lib/net-utils.js, packages/wmr/src/lib/normalize-options.js, packages/wmr/src/serve.js, packages/wmr/types.d.ts
=> Update Lighthouse CI start regex command

.changeset/spicy-hornets-provide.md, packages/create-wmr/tpl/tsconfig.json
Fixes https://github.com/preactjs/wmr/issues/259#issuecomment-805316476
JetBrains tools won't automatically load WMR's types, while I think VSCode and some others do. This should ensure better tooling parity.
Solution proposed by @danielweck https://github.com/preactjs/wmr/issues/259#issuecomment-805371513
=> fix: Ensures WMR types are available to user

.changeset/violet-grapes-sparkle.md, packages/wmr/src/bundler.js, packages/wmr/src/wmr-middleware.js
Regression was introduced with #465 (unreleased)
=> Fix wrong plugin ordering

packages/wmr/test/production.test.js
With `toBe()` we see nothing:
With `toMatch()` it prints both strings:
=> Use jest matchers to better inspect mismatches

.changeset/quiet-ways-attend.md, packages/wmr/src/lib/compile-single-module.js, packages/wmr/src/lib/normalize-options.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/config-node-builtins/index.html, packages/wmr/test/fixtures/config-node-builtins/wmr.config.mjs, packages/wmr/test/fixtures/config-node-builtins/wmr/a.mjs
~~Based on #476~~ - Ready to review!
=> Fix unable to use node builtins in config file

.changeset/wise-dragons-drum.md, packages/wmr/src/bundler.js, packages/wmr/src/lib/normalize-options.js, packages/wmr/src/lib/plugins.js, packages/wmr/src/wmr-middleware.js, packages/wmr/test/production.test.js, packages/wmr/types.d.ts
This PR unifies the plugin array in `wmrMiddleware` and `buildProd`. This ensures that we are more consistent between dev and prod, by injecting plugins at the same place.
~~Draft, because it's based on #478 and #477~~
=> Use the same plugin array in dev and prod

.changeset/curvy-adults-reflect.md, packages/wmr/src/lib/plugins.js
=> Bugfix: correctly invoke plugins when there are no enforce:post plugins

.changeset/mean-cycles-change.md, packages/wmr/src/lib/fs-watcher.js, packages/wmr/src/start.js, packages/wmr/src/wmr-middleware.js
I believe this should fix #499.
=> Bugfix: always set useFSEvents option for Chokidar

.changeset/dull-bags-attack.md, packages/wmr/package.json, packages/wmr/src/cli.js, packages/wmr/src/lib/prerender.js, packages/wmr/test/fixtures/prerender-crash/index.html, packages/wmr/test/fixtures/prerender-crash/index.js, packages/wmr/test/production.test.js, yarn.lock
Prerendering errors are Strings because they're sent from a Worker. This parses them back into Error objects and falsifies the `.stack` property so it gets pretty printed. It also adds a guard around the stack trace parsing, which was throwing an exception when we tried to give it an undefined `error.stack` (it expects a String).
=> Bugfix: show stack trace for prerendering errors instead of crashing

package.json
This makes it possible to work on docs by calling `yarn docs start`. The netlify script is already updated to use `yarn docs build`
=> Update docs command

.changeset/yellow-peas-decide.md, packages/preact-iso/router.js, packages/preact-iso/test/router.test.js
This prevents the Router's link handling from intercepting clicks on links with `<a target="anything">`. Only these cases will be intercepted:
```
<a />
<a target="self" />
<a target="_self" />
<a target="_SELF" />
```
Fixes #488.
=> [preact-iso] Router should ignore links with target=".."

.changeset/orange-numbers-jog.md, packages/create-wmr/tpl/_gitignore, packages/wmr/package.json, packages/wmr/rollup.config.js, packages/wmr/src/cli.js, packages/wmr/src/lib/plugins.js, packages/wmr/types.d.ts, yarn.lock
This adds a bundle visualizer behind the `--visualize` flag for `wmr build`. Visualizer plugin used: https://github.com/btd/rollup-plugin-visualizer
When ran, a `stats.html` file will be created in the root of the project and the file will be opened in the users' default user agent. They'll get a tree graph that will show the break down of their app rendered as well as with brotli and gzip. 
Seems like the most popular visualizer for Rollup, and is [on Vite's roadmap of plugins to cover](https://vite-rollup-plugins.patak.dev/#rollup-plugin-visualizer). This does increase the bundle as a bit as the template JS is ~82kb (mostly) unminified
=> (wmr): Adding bundle visualizer

.changeset/curvy-brooms-begin.md
Looks like I did the publish with an old `node_modules` folder. We should really switch to changesets publish action!
=> Fix bad publish of 1.5.0

.changeset/friendly-brooms-shout.md, packages/create-wmr/tpl/tsconfig.json
My fault, I copy/pasted that from some comment without manually checking. It'll "silence errors" only because `public` is then not included. If the users add this, the previous "fix" breaks.
=> create-wmr template: Fix file path in tsconfig

packages/create-wmr/tpl/tsconfig.json
Default behavior for `"include"` is `["**/*"]` ->  https://www.typescriptlang.org/tsconfig#include
Adding this will get that default back, while ensuring JetBrains IDEs include that ambient type declaration file. Else users will need to make sure to add `public` or other paths to their tsconfig
=> revert: Restoring default tsconfig include behavior

packages/preact-iso/README.md
the `lazy` imports in `preact-iso/Readme.md` are named, which is not what is exported.
=> fix lazy imports

.changeset/hot-rabbits-travel.md, packages/wmr/src/plugins/npm-plugin/registry.js
We only include files with extensions WMR can deal with, but we support WASM so it should be included.
=> Include .wasm files in streamed packages

.changeset/real-horses-promise.md, packages/preact-iso/router.js
=> [preact-iso] Support manual URL via <LocationProvider url="/" />

docs/public/components/theme-switcher.js, docs/public/index.html, docs/public/lib/use-localstorage.js
This fixes two things in the docs site:
1. The ThemeSwitcher was using the saved theme value from `localStorage` to render during initial page hydration, which causes a hydration mismatch when the theme is set to anything other than `"auto"` (the value we use during SSR).
> To work around this, I added a third boolean argument to `useLocalStorage()` that causes it to return the provided `initial` value during the first render to ensure hydration matches SSR, then immediately self-update with the localStorage value if one was set.
2. It adds a little inline JS snippet to `<head>` that applies any saved theme from localStorage before CSS loads, which eliminates the flash-of-auto thing.
Preview of both changes:
https://user-images.githubusercontent.com/105127/115053287-f95b3600-9eac-11eb-9c33 …
=> [docs] Fix ThemeSwitcher hydration mismatch

.changeset/twenty-onions-serve.md, packages/wmr/src/wmr-middleware.js
Currently `style.module.sass.js` and `style.module.scss.js` mapping get stale, so adding or changing class names in a sass-powered module file will not get acknowledged until full restart of wmr.
=> Clear up cached module.s[ac]ss module mappings

.changeset/shaggy-laws-cry.md, packages/wmr/src/plugins/wmr/styles-plugin.js
I've been using CSS Modules, which was effectively enabling this for me. I don't think we have any reason not to pass stuff through Stylis - it adds nesting support and whatnot.
=> Always run CSS through stylis to support nesting/etc

.changeset/red-windows-dream.md, packages/wmr/package.json, packages/wmr/src/build.js
We originally added `premove` as the recursive removal option for `fs.rmdir()` didn't come out until Node 12.10 and the engine requirements were only set to >=12. 
But with #546 now upping that to 12.17, we can swap out `premove` with the native method.
=> refactor: Swapping out premove with fs.rmdir

.changeset/big-dolls-hammer.md, packages/wmr/src/bundler.js, packages/wmr/src/lib/output-utils.js, packages/wmr/src/lib/plugins.js, packages/wmr/src/plugins/copy-assets-plugin.js, packages/wmr/src/plugins/htm-plugin.js, packages/wmr/src/plugins/npm-plugin/index.js, packages/wmr/src/plugins/sass-plugin.js, packages/wmr/src/plugins/sucrase-plugin.js, packages/wmr/src/plugins/unpkg-plugin.js, packages/wmr/src/plugins/wmr/plugin.js, packages/wmr/src/plugins/wmr/styles-plugin.js, packages/wmr/src/wmr-middleware.js
Preface: I'm not sure of the reason this was used to begin with, so it's possible I've missed something or that this isn't the best fix. Test suite passes, behavior seems right, but beyond that, quite unsure. 
Corrects WMR output when referencing imports. For example, this message was pulled from the slack: `... Error: Could not loadnpm/call-bind@1.0.2/./ (imported bynpm/call-bind@1.0.2/callBound.js): ...`. The backspace character in the NPM prefix (`\bnpm`) would cause the output to be shown incorrectly like this (`loadnpm/...`, `bynpm/...`).
This PR simply removes the backspace character from the prefixes and the places it is checked for.
As far as I know, `PREFIX_INTERNAL` wasn't an issue / ever shown, but due to the shared regex between the prefixes, I changed both.
=> fix: Error messages by removing the backspace character from npm prefix

.changeset/thirty-poets-fry.md, packages/preact-iso/router.js, packages/preact-iso/test/router.test.js
The following snippet lead to a crash:
```jsx
<Router>
<Route path="/" />
{["a", "b"].map(x => <Route path={`/${x}`} />}
{condition && <Route path="/boof" />}
</Route>
```
There error was caused because we didn't normalize children at all.
=> Fix crash when passing array children to preact-iso

.changeset/gorgeous-scissors-compete.md, packages/preact-iso/router.js, packages/preact-iso/test/match.test.js, packages/preact-iso/test/router.test.js
When a query param was named the same as an existing key on the route like "path", we'd overwrite that.
Imagine that we are on `/foo/bar` as the url and our route looks like this:
```jsx
<Route path="/foo/:id" ... />
// -> { path: "/foo/bar", query: {}, id: "bar" }
```
But when we name the param the same as an existing key we'd overwrite those:
```jsx
<Route path="/:path/:query" ... />
// -> { path: "bar", query: "bar" }
```
By moving params to their own object we avoid that issue all together. This is also in line with how most other routers in the wild store params.
```jsx
<Route path="/:path/:query" ... />
// -> { path: "/foo/bar", query: {}, params: { path: "foo", query: "bar" }}
```
=> Fix route params overwriting route properties

.changeset/chilled-fishes-work.md, packages/wmr/src/plugins/wmr/client.js, packages/wmr/src/start.js
This PR adds a simple error overlay that is displayed on build errors.
Light:
Dark:
=> Add error overlay during development

.changeset/four-starfishes-begin.md, packages/wmr/src/plugins/html-entries-plugin.js
=> Don't partially indent code frame on html warnings

.changeset/fluffy-lamps-smile.md, packages/preact-iso/index.d.ts, packages/preact-iso/router.d.ts
- Fix missing `useRoute` and `RouterProps` in types
- Strongly type return value of `useRoute`
- Remove deprecated `useLoc` type
=> Update preact/iso TypeScript types

.changeset/breezy-dolphins-retire.md, packages/wmr/src/cli.js, packages/wmr/test/fixtures/script-type/public/foo.js, packages/wmr/test/fixtures/script-type/public/index.html, packages/wmr/test/fixtures/script-type/public/index.js, packages/wmr/test/production.test.js, packages/wmr/test/test-helpers.js
This PR fixes a regression introduced in #561. There the logic assumed that the full error message would always be the first line of `error.stack`.
This is not universally true and most errors thrown by us spans multiple lines by default. With our previous logic we only showed a tiny part of the message.
Before:
After:
The new logic leverages our stack trace parser to determine the offset of when it finds an actual location and assumes that everything before that must be the message.
Added a test to catch that in the future.
=> Fix missing build errors in terminal output

.changeset/afraid-goats-occur.md, packages/preact-iso/lazy.js
This prevents ErrorBoundary from pushing objects into the commit queue, which only handles functions (it tries to call `item.call(component)` where `item` is an object.
=> preact-iso: fix ErrorBoundary pushing object into commit queue

.changeset/tiny-phones-mate.md, packages/wmr/src/build.js, packages/wmr/src/lib/output-utils.js, packages/wmr/test/production.test.js
I'm always unsure if the generated files on build are as expected without looking manually, as our output filters out all non-css assets.
This PR changes that, but keeps the group intact, so that code files are at the top.
Before:
After:
=> Show all generated files on build

.changeset/chatty-scissors-protect.md, docs/package.json, docs/public/components/meta.js, docs/public/prerender.js, examples/demo/package.json, examples/demo/public/header.tsx, examples/demo/public/index.tsx, examples/demo/public/pages/meta-tags.js, packages/wmr/src/lib/prerender.js, packages/wmr/src/plugins/optimize-graph-plugin.js, packages/wmr/src/plugins/wmr/client-prod.js, packages/wmr/test/fixtures/prerender-external/index.js, packages/wmr/test/fixtures/prod-head/index.js, packages/wmr/test/fixtures/prod-prerender-json/index.js, packages/wmr/test/production.test.js, yarn.lock
Prerendering of meta tags and other elements in the documents head previously worked by relying on a custom implementation of the global `document` object. We only did add a tiny subset of the methods that are available in the browser, but doing so breaks nearly all server detection code in third party libs. Checked various libraries and the most common snippet to do that is a variation of:
```js
// This was always false in wmr because we supply a fake document global
const isServer = typeof document === "undefined";
```
Because we did patch in a global document object, this value is always `false`, even during SSR.
Another problem with that approach in genral is that we'll always have a biased subset of the API that may work with our code, but is not guaranteed to work with third-party …
=> Prerendering: Remove incomplete fake document

.changeset/light-ravens-design.md, packages/wmr/src/build.js
Stumbled across an issue over on the Vite repo asking for the output directory to be emptied without deleting the directory itself. This came from a user who had an containerized environment and the build output directory was a mount point. Simply deleting the directory caused issues in their setup.
https://github.com/vitejs/vite/issues/709
That's something our users could potentially run into as well, so I thought it made a fitting change. Not quite as nice, as it'll need to scan for each of the top-level items and clear them out, slightly slower too, but so long as the directory doesn't have a ton of top-level items it shouldn't be noticeable.
=> refactor: Clear output directory without deleting it

packages/wmr/src/build.js, packages/wmr/src/lib/fs-utils.js, packages/wmr/src/lib/normalize-options.js
@rschristian's #578 gave me an idea: we have a few cases where soon we'll be able to move to some of the lovely Node 14+ `fs.*()` methods like `fs.rm(p,{recursive:true})`, but for now we need to support Node 12. Adding a little "fs helpers" lib will make this super easy to change in the future, and lets us use the methods now.
=> Add filesystem helpers

packages/wmr/src/build.js
Fix a regression introduced in #580.
Node's `fs.rm()` function only deletes directories when `recursive: true` is set. This error occured in a few past CI runs since merging #580 and I can reproduce it locally when running our test suite.
Proof: https://github.com/nodejs/node/blob/18e4f405b14b26f971d5f108b92224e7c1fe34c9/lib/internal/fs/utils.js#L746
=> Fix ERR_FS_EISDIR error on rebuilds

.changeset/sweet-tables-impress.md, packages/wmr/src/wmr-middleware.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/virtual-id/public/index.html, packages/wmr/test/fixtures/virtual-id/public/index.js, packages/wmr/test/fixtures/virtual-id/wmr.config.mjs, packages/wmr/test/production.test.js
This PR allows plugins to pick any name for a virtual module instead of having to dance around our npm or prefix detection logic. They can now just be named `my-virtual-module` or `@my-virtual-module` for example and it works out of the box. This is the main friction point I run into over and over whenever I play with custom plugins.
```js
{
name: 'my-plugin',
resolveId(id) {
if (id === 'my-module') {
return id;
}
},
load(id) {
if (id === 'my-module') {
return `export const foo = 42`;
}
}
}
```
The detection is based on the return value of `load()`. In the case of virtual modules we'd return a non-null result, since plugins neat to load that. When the return value is `null` we therefore know that the passed `id` can't be a virtual module and therefore must refer to an npm package. …
=> Fix bare specifiers always rewritten as npm packages

packages/create-wmr/src/index.js, packages/create-wmr/tpl/package.json
So as it turns out, `pkg-install` does in fact write to the `package.json` file.... so long as you remember to scaffold your project before installing 🙃
`create-wmr` now installs the very latest versions of the deps and it will end up in the user's package file in the form of `"^x.x.x"`
=> create-wmr: template dep versions automatically kept up-to-date

.changeset/fast-lions-explain.md, packages/create-wmr/tpl/public/index.js
Although our current template is JS-only, I'd expect a good portion (if not most) of our users to opt into TypeScript. We do leverage some trickery to make a global `path` prop work, but it's more consisten with other components to opt for  `Route` instead.
In most user's mind a JSX element is equivalent to a function call and in that model it's strange to see additional props besides ref/key.
=> Use Route components in template for potential TS users

.changeset/long-moons-think.md, examples/demo/public/index.tsx, packages/preact-iso/prerender.js, packages/wmr/src/lib/prerender.js, packages/wmr/test/fixtures/prerender-data/index.html, packages/wmr/test/fixtures/prerender-data/index.js, packages/wmr/test/production.test.js
This add support for returning a `data` key from the prerender, this enables us to for instance use [prepass](https://github.com/preactjs/preact-ssr-prepass) or a manual `fetch` call to get some data needed for rendering.
=> Support returning prerender data

.changeset/calm-olives-allow.md, packages/preact-iso/router.js, packages/preact-iso/test/router.test.js
This was using `useEffect()` to register the handler, but that waits 1 rAF. During the frame delay, clicks are ignored by the router.
=> (preact-iso): register link click handler immediately to prevent race condition

.changeset/long-seas-tan.md, packages/create-wmr/tpl/wmr.config.mjs
This was caused by mixed module syntaxes.
=> Fix unable to start starter template

.changeset/neat-carrots-teach.md, packages/wmr/src/plugins/copy-assets-plugin.js
Currently if a user has a `.d.ts` file in their app, it will be automatically copied into the build output. Sometimes nice to use them for super common app-wide types. Skips an import.
I just ended up mimicking an exclusion that was already there for dotfiles.
=> fix: Ensuring .d.ts files aren't copied to build output

.changeset/good-beans-add.md, packages/directory-plugin/src/index.js, packages/wmr/test/fixtures/directory-import/public/foo/a.js, packages/wmr/test/fixtures/directory-import/public/foo/b.js, packages/wmr/test/fixtures/directory-import/public/foo/c.js, packages/wmr/test/fixtures/directory-import/public/index.html, packages/wmr/test/fixtures/directory-import/public/index.js, packages/wmr/test/fixtures/directory-import/public/invalid.js, packages/wmr/test/fixtures/directory-import/wmr.config.mjs, packages/wmr/test/plugins/directory-plugin.test.js, packages/wmr/test/test-helpers.js
Rollup's `PluginContext.resolve()` does not resolve directories, whereas our dev-time version does (because it doesn't/can't check for existence). Using `path.resolve()` fixes this.
**Note: I have not yet tested that this PR works!**
=> Fix directory plugin not resolving in prod builds

.changeset/silver-needles-grin.md, packages/wmr/src/cli.js
Few issues this solves:
* `yarn wmr serve --help` printed out two competing descriptions for the `--out` flag (1 global, 1 local)
* `--public` isn't relevant for `serve`'s functionality
*  `--out` for the dev server seems kind of odd and not intended? Basically `.cache/` will contain only the node modules (`@npm/`) while all the app stuff gets moved into whatever the `--out` dir is set to. Spreads the contents of `.cache/` over two directories which seems like an odd thing to want.
=> (wmr): Fix cli flags

.changeset/early-masks-mix.md, packages/wmr/package.json, packages/wmr/rollup.config.js, packages/wmr/src/lib/npm-middleware-cache.js, packages/wmr/src/plugins/fast-minify.js, yarn.lock
Terser 5 made the `minify()` method async. It's still the same fully synchronous code, just they updated their version of `source-map` to the one that uses WASM, which requires waiting for that to initialize.
---
**What's with the timings?** Originally, this upgrade caused all our `minify()` logs to show minification taking >1s, however after investigating and comparing with a modified synchronous version of Terser, this ended up being a miscalculation. Because Terser is still fully synchronous (we don't even hit the async codepath), timing the `await minify()` was effectively timing all enqueued minify() jobs. This happens because minify is an async function, but Rollup invokes `renderChunk()` in parallel within a synchronous loop. This loop basically enqueues a `minify()` task for all …
=> Upgrade to Terser 5.7.0

.changeset/light-flies-melt.md, .changeset/silver-ways-lie.md, docs/public/content/docs/configuration.md, examples/demo/wmr.config.ts, packages/wmr/src/lib/aliasing.js, packages/wmr/src/lib/normalize-options.js, packages/wmr/src/lib/npm-middleware.js, packages/wmr/src/lib/output-utils.js, packages/wmr/src/lib/plugins.js, packages/wmr/src/plugins/aliases-plugin.js, packages/wmr/src/plugins/url-plugin.js, packages/wmr/src/plugins/wmr/styles-plugin.js, packages/wmr/src/server.js, packages/wmr/src/wmr-middleware.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/alias-asset/wmr.config.mjs, packages/wmr/test/fixtures/alias-css/wmr.config.mjs, packages/wmr/test/fixtures/alias-deprecated/public/index.html, packages/wmr/test/fixtures/alias-deprecated/public/index.js, packages/wmr/test/fixtures/alias-deprecated/wmr.config.mjs, packages/wmr/test/fixtures/alias-outside/wmr.config.mjs, packages/wmr/test/fixtures/alias-parent/wmr.config.mjs, packages/wmr/types.d.ts
As @rschristian noticed in #552 we sometimes check for `alias` and sometimes for `aliases`. We should only have one name for that feature. Just checked with other bundlers and the majorities use `alias`:
| Tool | Naming |
|---|---|
| [webpack](https://webpack.js.org/configuration/resolve/#resolvealias) | `alias` |
| [Parcel](https://parceljs.org/module_resolution.html#aliases) | `alias` |
| [vite](https://vitejs.dev/config/#resolve-alias) | `alias` |
| wmr | `alias` in `package.json`, otherwise `aliases` |
So to be consistent with everyone else (and ourselves), this PR deprecates `options.aliases` in favor of `options.alias`. Setting up aliasing via `options.aliases` will continue to work, but we'll print a deprecation warning to the console.
```bash
Deprecated: Found "aliases" property …
```
=> Deprecate `options.aliases` in favor of `options.alias`

.changeset/sixty-needles-change.md, packages/wmr/src/lib/normalize-options.js
This was an interesting one! Essentially we land in an undefined situation with our current plugin system. We pass the options object directly to the configuration to plugins, but we ignore the fact that plugins may lazily change them. This leads to an awkward scenario where the passed reference may get out of sync.
```js
export function options => {
myPlugin(options.cwd) // out of sync
}
```
This requires a bit more brain power to solve once and for all, but for now this PR gets our docs site up and running again.
=> Fix broken docs build

.changeset/modern-dolphins-talk.md, packages/wmr/src/lib/normalize-options.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/config-multiple/index.html, packages/wmr/test/fixtures/config-multiple/wmr.config.js, packages/wmr/test/fixtures/config-multiple/wmr.config.mjs, packages/wmr/test/fixtures/config-multiple/wmr.config.ts
Fixes the following error:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/marvinhagemeister/dev/github/wmr/examples/demo/wmr.config.js' imported from /Users/marvinhagemeister/dev/github/wmr/packages/wmr/src/lib/normalize-options.js
at new NodeError (node:internal/errors:329:5)
at finalizeResolution (node:internal/modules/esm/resolve:323:11)
at moduleResolve (node:internal/modules/esm/resolve:758:10)
at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:869:11)
at Loader.resolve (node:internal/modules/esm/loader:86:40)
at Loader.getModuleJob (node:internal/modules/esm/loader:230:28)
at Loader.import (node:internal/modules/esm/loader:165:28)
at importModuleDynamically (node:internal/modules/esm/translators:116:35)
at exports.importModuleDynamicallyCallback …
```
=> Only load first matching config file

.changeset/great-icons-drop.md, packages/wmr/src/plugins/optimize-graph-plugin.js
`hasDebugFlag()` partially relies on `debugCliArg`, which can only be truthy after `normalize-options` is ran. `DEBUG` being assigned at the module level here means it gets its value before `normalize` and sticks with it even after.
Simply pushed the assignment back a bit
=> (wmr): Fix debug in optimize-graph when debug is set via flag

.changeset/eight-peas-reflect.md, packages/wmr/src/plugins/copy-assets-plugin.js
This happens when there is no `public` or `src` dir.
=> Never copy wmr.config.js to output directory

.changeset/hungry-students-pump.md, packages/wmr/src/lib/polkompress.js, packages/wmr/test/lib/polkompress.test.js
Ok, this one is a little long-winded:
The `polkompress` middleware didn't always "cleanup"/terminate the response correctly. Basically, our monkey-patched `res.writeHead` held a dangling `pendingStatus` value for when `start()` was done. However, this only worked if there was an _explicit_ call to `res.writeHead` somewhere in the application _before_ the `start()` exits.
I don't know if this just has to do with the fact that my test case used a small `body`  (even when crossing the threshold) , but in my reproductions I saw that this was always the order:
```js
INSIDE END // via res.end patch
START END { pendingStatus: undefined } // last line of start()
INSIDE WRITEHEAD 200 // via res.writeHead patch
```
So, the `res.writeHead` call that `res.end` makes internally (native, not patched …
=> fix(polkompress): avoid hanging requests and/or runtime errors

packages/wmr/src/plugins/fast-minify.js
There's an undocumented option, `options.format.code`, which you can set to false to have Terser not output any code. In that case `out.code` is indeed undefined. It can be used if you're interested in the ESTree AST only (it's helpful if you want to do further processing to the code).
Side note, the Rust port of Terser built by the SWC project (which I've been neglecting a bit but I try to help out) is approaching a ready status. If you'd like to access an experimental version, let me know.
Much love!
=> Terser's typings are (technically) correct

.changeset/sour-keys-attend.md, packages/wmr/src/plugins/optimize-graph-plugin.js
If `/public/index.html` does not have entry CSS file like this..
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>repro</title>
</head>
<body>
<script type="module" src="/index.js"></script>
</body>
</html>
```
w/ minimal `/public/index.js`.
```js
import { hydrate, prerender as ssr } from 'preact-iso';
const App = () => <h1>Hello World!</h1>;
hydrate(<App />);
export const prerender = async (data) => ssr(<App {...data} />);
```
`wmr build --prerender` generates this HTML.
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>repro</title>
<link rel="stylesheet" href="/undefined"> 
</head>
<body><h1>Hello World!</h1>
<script type="module" src="/index.68215b6e.js"></script>
</body>
</html>
```
This empty `link` element should not be …
=> Do not inject link tag if entry css not exists

.changeset/poor-fireants-own.md, packages/wmr/src/lib/plugins.js, packages/wmr/src/plugins/resolve-extensions-plugin.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/import-priority/foo.js, packages/wmr/test/fixtures/import-priority/foo.ts, packages/wmr/test/fixtures/import-priority/index.html, packages/wmr/test/fixtures/import-priority/index.js
=> Add support for prioritizing extension resolve order

.changeset/ninety-cherries-hammer.md, packages/wmr/src/wmr-middleware.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/plugin-resolve-prefix/public/index.html, packages/wmr/test/fixtures/plugin-resolve-prefix/public/index.js, packages/wmr/test/fixtures/plugin-resolve-prefix/wmr.config.mjs, packages/wmr/test/fixtures/plugin-resolve/public/index.html, packages/wmr/test/fixtures/plugin-resolve/public/index.js, packages/wmr/test/fixtures/plugin-resolve/wmr.config.mjs, packages/wmr/test/production.test.js
This PR ensures that we keep passing relative import specifiers to resolveId. Previously we'd loose the leading `./`, leading to `./foo.js` being passed as `foo.js` during development.
This is a necessary precursor step towards turning the npm middleware into a standard plugin.
=> Fix relative import specifiers becoming bare in development

.changeset/early-vans-fail.md, packages/create-wmr/tpl/package.json
Probably fair to mark newly created wmr apps as being private, not for publish on NPM
Yarn will alert the user to this on every single command, which tends to get mildly annoying after a certain point
=> chore: Init'd create-wmr app is private by default

docs/plugins/markdown.js, docs/public/styles/index.css
When clicking on an anchor link the target headline was always hidden behind our fixed header. With some CSS magic we can add an offset to the scroll position to ensure the headline is in the visible area.
Before:
After:
=> Docs: Fix anchor links hidden behind header

.changeset/good-apricots-hide.md, .changeset/nine-emus-joke.md, docs/public/content/docs/configuration.md, packages/directory-plugin/src/index.js, packages/wmr/src/build.js, packages/wmr/src/bundler.js, packages/wmr/src/lib/compile-single-module.js, packages/wmr/src/lib/normalize-options.js, packages/wmr/src/lib/plugins.js, packages/wmr/src/plugins/copy-assets-plugin.js, packages/wmr/src/plugins/html-entries-plugin.js, packages/wmr/src/plugins/json-plugin.js, packages/wmr/src/plugins/url-plugin.js, packages/wmr/src/plugins/wmr/styles/styles-plugin.js, packages/wmr/src/server.js, packages/wmr/src/start.js, packages/wmr/src/wmr-middleware.js, packages/wmr/test/boot.test.js, packages/wmr/test/environment.test.js, packages/wmr/test/fixtures/plugin-hooks/public/index.html, packages/wmr/test/fixtures/plugin-hooks/wmr.config.mjs, packages/wmr/test/plugins/plugins.test.js
This PR corrects the swapped usage of `options.cwd` vs `options.root`. The former is now always equal to the current working directory and `options.root` points to the absolute public dir (=usually `<cwd>/public`).
Marking as major, because users might have worked around the swapped usage in custom plugins and doing this in a non-major release would break their config.
For the directory plugin a major release is not necessary, because npm treats minor versions below `< 1.0.0` as major and won't update to that automatically.
Fixes #142
=> Fix swapped usage of `options.cwd` vs `options.root`

.changeset/shiny-adults-brake.md, packages/wmr/package.json, packages/wmr/src/lib/npm-middleware.js, packages/wmr/src/lib/plugins.js, packages/wmr/src/lib/rollup-plugin-container.js, packages/wmr/src/plugins/sass-plugin.js, packages/wmr/src/plugins/wmr/client.js, packages/wmr/src/plugins/wmr/styles/styles-plugin.js, packages/wmr/src/wmr-middleware.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/css-module/foo.module.css, packages/wmr/test/fixtures/css-module/index.html, packages/wmr/test/fixtures/css-module/index.js, packages/wmr/test/fixtures/css-sass-module/public/index.html, packages/wmr/test/fixtures/css-sass-module/public/index.js, packages/wmr/test/fixtures/css-sass-module/public/style.module.scss, packages/wmr/test/fixtures/css-sass/public/index.html, packages/wmr/test/fixtures/css-sass/public/style.scss, yarn.lock
Completely rewrite our stylesheet pipeline. All CSS files can now be intercepted from plugins allowing us to leverage the same pipeline that we use for production during development.
- Fixes `.scss/.sass` not compiled on watch
- Fixes nested `.scss/.sass` files not compiled with sass
- Fixes `.scss/.sass` files not compiled when directly referenced in HTML
- Fixes asset caching overwriting each others entries
- Adds groundwork for intercepting urls inside css for aliasing (#685) or resolving from `node_modules` (didn't want to make this PR even larger, will come in a next PR)
Notes:
- Proxy modules `foo.module.css.js` are now specified by a query param: `foo.module.css?module`.
- Assets now have hashes to avoid collisions in our cache. We had assets that overwrote each others entries
This …
=> Rewrite styles pipeline to get rid of transform abstraction for CSS

.changeset/seven-moons-fail.md, packages/wmr/src/lib/plugins.js, packages/wmr/src/plugins/sass-plugin.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/css-sass-alias/foo/foo.scss, packages/wmr/test/fixtures/css-sass-alias/public/index.html, packages/wmr/test/fixtures/css-sass-alias/public/style.scss, packages/wmr/test/fixtures/css-sass-alias/wmr.config.mjs
This allows sass to load aliased files and anything else plugins might resolve an url to.
Based on #684
Fixes #645, fixes #642 .
=> Sass: Add support for resolving imported paths

.changeset/old-toys-divide.md, packages/wmr/src/lib/normalize-options.js, packages/wmr/test/environment.test.js, packages/wmr/test/fixtures/env-precedence/.env, packages/wmr/test/fixtures/env-precedence/index.html, packages/wmr/test/fixtures/env-precedence/index.js, packages/wmr/test/fixtures/env-precedence/wmr.config.mjs
Explicit environment variables passed via the CLI should always take precedence over anything else.
```sh
WMR_FOO="foo" wmr start
```
=> Fix CLI environment variables overwritten by .env files

packages/wmr/test/css.test.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/test-helpers.js
This PR extracts the CSS tests to a separate file. This makes them easier to run separately and the `fixtures.test.js` file has gotten pretty long anyway.
We also benefit from quicker test times as jest parallelizes files.
=> Extract CSS tests

.changeset/ninety-moles-sparkle.md, packages/wmr/src/lib/rollup-plugin-container.js, packages/wmr/src/plugins/wmr/styles/styles-plugin.js, packages/wmr/src/wmr-middleware.js, packages/wmr/test/css.test.js, packages/wmr/test/fixtures/css-module-clash/public/bar/bar.js, packages/wmr/test/fixtures/css-module-clash/public/bar/styles.module.css, packages/wmr/test/fixtures/css-module-clash/public/foo/foo.js, packages/wmr/test/fixtures/css-module-clash/public/foo/styles.module.css, packages/wmr/test/fixtures/css-module-clash/public/index.html, packages/wmr/test/fixtures/css-module-clash/public/index.js
Fix potential issue during development, where different CSS assets would share the same URL. This occured whenever multiple CSS files had the same filename.
=> Fix CSS assets sharing same URL

.changeset/kind-carrots-beg.md, packages/wmr/src/wmr-middleware.js
With the recent CSS pipeline refactoring some urls can contain search parameters. Problem is that the `?` and `&` are invalid characters for file paths.
This seems to work just fine on macOS or Linux, but leads to a crash on Windows.
While investigation further it turns out that we actually don't need to write those files to disk at all because we've never read them anywhere. Instead we just serve from memory directly.
The only exception to that is the npm middleware, but that implements its own caching logic and is therefore not affected by this PR.
=> Fix crash on Windows due to invalid cache file paths 

.changeset/tiny-pants-cry.md, packages/wmr/src/plugins/sass-plugin.js
Weirdly `node-sass` always returns unix-style paths so we need to normalize those ourselves.
The same workaround can be found in webpack's `sass-loader`: https://github.com/webpack-contrib/sass-loader/blob/38fa37e99aae3af25d15cc51d37bcdc1b23c7227/src/index.js#L59
=> Sass: Fix HMR not working on windows

.changeset/tricky-numbers-bow.md, packages/wmr/src/plugins/sass-plugin.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/css-sass-alias-relative/public/index.html, packages/wmr/test/fixtures/css-sass-alias-relative/public/style.scss, packages/wmr/test/fixtures/css-sass-alias-relative/src/bar.scss, packages/wmr/test/fixtures/css-sass-alias-relative/src/foo.scss, packages/wmr/test/fixtures/css-sass-alias-relative/wmr.config.mjs
Fix relative import specifiers in the form of `./foo.scss` being resolved against the wrong directory.
=> Sass: Fix full relative paths resolved in wrong directory

.changeset/cold-cougars-jog.md, packages/wmr/package.json, packages/wmr/src/lib/acorn-default-plugins.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/logical-assignment/index.html, packages/wmr/test/fixtures/logical-assignment/index.js, yarn.lock
Add support for logical assignment operators.
```js
// "Or Or Equals" (or, the Mallet operator :wink:)
a ||= b;
a || (a = b);
// "And And Equals"
a &&= b;
a && (a = b);
// "QQ Equals"
a ??= b;
a ?? (a = b);
```
=> Add support for logical assignment

packages/wmr/src/plugins/process-global-plugin.js
Currently this doesn't lead to an issue, because we only pass js and style files through our plugin system. It will become an issue once we open it up for more file types in the future though.
=> Fix wrong regex in process global plugin

packages/wmr/src/wmr-middleware.js
The outer function already handles `ENOENT` codes
=> Remove duplicate error handling

.changeset/curly-panthers-trade.md, packages/wmr/src/wmr-middleware.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/markdown/foo.md, packages/wmr/test/fixtures/markdown/index.html, packages/wmr/test/fixtures/markdown/index.js, packages/wmr/test/fixtures/markdown/wmr.config.mjs, packages/wmr/test/production.test.js
This PR adds support for passing any file forward to plugins. This allows plugins to intercept all kinds of files. The only exception to that are html files for now.
Fixes #721 .
=> Add support for passing any file to plugins

.changeset/strange-olives-destroy.md, packages/wmr/src/plugins/process-global-plugin.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/process-object/index.html, packages/wmr/test/fixtures/process-object/index.js
Fix `Cannot read property 'edit' of null` error. This was caused by a wrong alternative to substring matches of `String.prototype.replace`.
This is a regression that was introduced with #715
=> Fix regression in process plugin

packages/wmr/src/lib/acorn-traverse.js, packages/wmr/src/lib/npm-middleware.js, packages/wmr/src/plugins/npm-plugin/index.js, packages/wmr/src/serve.js, packages/wmr/src/server.js, packages/wmr/src/wmr-middleware.js
The type `ReturnType` only works on types, not on values. A function definition is by default a value and not a type, therefore we need to convert it to a type first via `typeof`.
This fixes intellisense for those type and the popup that shows up when you hover it.
// cc @developit
=> Fix invalid TypeScript ReturnType parameter

packages/wmr/src/lib/acorn-traverse.js, packages/wmr/test/acorn-traverse.test.js
This is needed for our babel plugin for component stack traces.
=> Add filename to plugin state

packages/wmr/test/preact.test.js
This fixes flaky test runs on my windows machine
=> Fix flaky HMR test by waiting until full page load

docs/public/components/home-page.js, docs/public/styles/index.css
The sidebar comes in before the content when clicking "Get Started". This animation makes that feel a little nicer.
I was slightly worried about what happens on initial page load / reloads directly on `/docs` pages though.
=> [docs] Slide in sidebar when first shown

.changeset/clean-crabs-wait.md, packages/wmr/src/lib/prerender.js, packages/wmr/test/fixtures/prerender-missing-export/index.html, packages/wmr/test/fixtures/prerender-missing-export/index.js, packages/wmr/test/production.test.js
Addresses the other part of #749 (I think).
=> Improve error message when prerender() is not exported

.changeset/grumpy-dingos-admire.md, package.json, packages/wmr/package.json, packages/wmr/src/plugins/fast-cjs-plugin.js, packages/wmr/src/plugins/wmr/styles/styles-plugin.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/typescript-override/index.html, packages/wmr/test/fixtures/typescript-override/index.ts, yarn.lock
This PR adds support for the `override` keyword on class methods. Note that I had to update `prettier` too, because our previous version would error when encountering `override`.
Fixes #714 .
=> TypeScript: Add support for `override` keyword

packages/wmr/src/lib/acorn-traverse.js, packages/wmr/test/acorn-traverse.test.js
This PR makes both `template` and `template.ast` work without generating invalid code.
The problem occurs due to the optimization where we try to re-use the original code and slice output from that. The heuristic is based on whether a node has position data or not. But with `template`, `template.ast` or `t.clone()` it always has position data leading to wrong results.
The fix here adds a `forceRegenerate` flag that skips this optimization for `path.replaceWith`. The other option would be to visit each node of the replaced tree and delete the position data.
- Fixes crash when template string contained unrelated uppercase latters
- Fix invalid code generated by `path.replaceWith` when invoked with nodes that contain position data.
- Overwrite `ObjectExpression` codegen to be roughly more in …
=> Fix invalid code generated by template helper

.changeset/four-comics-run.md, packages/wmr/types.d.ts
Went with inlining those types as suggested in #748 as we only use a small portion of polka's types.
Fixes #748 .
=> Fix incorrect middleware typings

.changeset/eighty-months-explain.md, packages/wmr/src/server.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/middleware-custom/bar.js, packages/wmr/test/fixtures/middleware-custom/foo.js, packages/wmr/test/fixtures/middleware-custom/index.html, packages/wmr/test/fixtures/middleware-custom/index.js, packages/wmr/test/fixtures/middleware-custom/wmr.config.mjs
Similar to custom plugins, custom middlewares are now handled before our own internal ones. This allows requests to be intercepted which wasn't possible before.
Fixes #297 .
=> Fix unable to intercept wmr middleware

packages/wmr/src/lib/acorn-traverse.js, packages/wmr/test/acorn-traverse.test.js
This lays the foundation for scope tracking in our acorn transformation layer. It includes a better fix for the `parentPath` issue than #763 which is coincidentally tested with the scope tracking stuff.
_FYI: This doesn't implement the second parsing pass that's needed to collect all references in scope, that will come best with the next PR_
=> Add support for scope tracking

.changeset/rare-cars-exercise.md, packages/wmr/package.json, yarn.lock
This was an upstream issue in `acorn-import-assertion` which was patched by @riywo 🎉 
Fixes #769
=> Fix ImportSpecifier's wrongly detected as assert keyword

.changeset/gold-candles-sing.md, packages/wmr/src/lib/acorn-traverse.js
This should fix the issue @Inviz reported in chat. It might be worth checking how we're ending up passing `null`/`undefined` to `isIdentifier()`, but my guess is that it happens when we're [iterating over the elements of an assignment pattern](https://github.com/preactjs/wmr/blob/1055e92d44f2c4def74127d1653fa3f046c8379a/packages/wmr/src/lib/acorn-traverse.js#L1045) and the pattern has "holes" (which IIRC show up as `elements:[undefined,undefined,b]`):
```
const [, , b] = c;
```
```
500 ./public/components/a/index.js - Cannot read property 'type' of undefined
at Proxy.isIdentifier (/Users/imac/Sites/medes/web/frontend/node_modules/wmr/wmr.cjs:2:960601)
at o (/Users/imac/Sites/medes/web/frontend/node_modules/wmr/wmr.cjs:2:962216)
at o …
```
=> Avoid isIdentifier() crash on null/undefined values

.changeset/dull-otters-attack.md, packages/wmr/src/plugins/sass-plugin.js
Fixes: https://github.com/preactjs/wmr/issues/771
We were emitting the asset but rollup does not push that through the plugin-pipeline, hence why this is now happening as a post-step when generating the final bundle.
=> Transpile scss files included from html

.changeset/fuzzy-files-fail.md, packages/sw-plugin/src/index.js
This fixes #794. There were two bugs:
1. the child rollup build was looking for `${options.cwd}/${id}`, which means it wasn't respecting `public/`.
2. The plugin was relying on `writeCacheFile()` actually writing to disk - writing into `WRITE_CACHE` doesn't seem to allow intercepting `.js` requests, so the request for the generated `_sw.js` asset (not module) was being handled by the `js` handler. This just appends `?asset` to the generated URL in development (not in prod.
=> Fix Service Worker plugin

.changeset/fuzzy-masks-allow.md, packages/wmr/src/plugins/wmr/client.js
Related to #800 
It's come up a few times now in our tracker as well as the Slack that Preact-CLI's debug service worker will cause issues if still active when using WMR. As there's going to be a fair bit of overlap between Preact-CLI and WMR's users, I think this is a common enough situation to justify handling. Even for those that recognize this issue and know how to handle it, this should save opening the dev tools and unregistering manually.
Hopefully this approach isn't too naive, though I'm not sure if there's any better way to target it.
[Preact-CLI also uses `sw.js` and `sw-esm.js`](https://github.com/preactjs/preact-cli/blob/b3b6984a1d022ac3348784061bd8864f66f2d670/packages/cli/lib/lib/entry.js#L10-L29), though no one has brought up issues with them yet as far as I'm aware …
=> fix: Unregister preact-cli's service worker if active

.changeset/seven-birds-refuse.md, packages/wmr/src/lib/acorn-traverse.js
When building a JSX node with an object with more than 5 properties and a JSX prop, this fixes the following error:
```
TypeError: this[node.value.type] is not a function
```
Creating a new wmr project with the following `public/index.js` currently fails:
```
export function App() {
return (
<div
style={{
top: 0,
bottom: 0,
left: 0,
right: 0,
position: "relative",
display: "block",
}}
children={<hr />}
/>
);
}
```
If the children prop is placed before the style prop, the build succeeds.
This was introduced in https://github.com/preactjs/wmr/commit/2bfb296030be42b3b2ac81e49c98f4cb43033892
=> Fix building JSX that contains a large object (>5 properties) then JSX in a prop

.changeset/spicy-cars-study.md, packages/wmr/src/plugins/html-entries-plugin.js, packages/wmr/test/production.test.js
This PR fixes an incorrect file extension with production builds, when a `.scss` file was directly referenced in the HTML. It would keep the `.scss` extension and didn't rename the asset to `.css`.
=> Fix sass files not renamed to css in prod if directly referenced in html

.changeset/cyan-timers-jump.md, packages/wmr/src/plugins/wmr/styles/styles-plugin.js, packages/wmr/src/wmr-middleware.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/virtual-id-at/public/index.html, packages/wmr/test/fixtures/virtual-id-at/public/index.js, packages/wmr/test/fixtures/virtual-id-at/wmr.config.mjs, packages/wmr/test/production.test.js
There is `rollup-plugin-windicss` which has chosen a virtual identifier that includes a leading slash `/@windicss/windi.css` this is very unfortunate as that character normally means "resolve from the public dir" in our case since we view it through the lens of a webserver.
To workaround that I've added a special case for urls where the leading slash is immediately followed by an at sign `/@`.
Fixes #811
=> Fix virtual specifiers starting with `/@` not being supported

.changeset/metal-ties-run.md, packages/wmr/src/plugins/wmr/styles/styles-plugin.js, packages/wmr/test/css.test.js, packages/wmr/test/fixtures/css-module-compose-warn/foo.css, packages/wmr/test/fixtures/css-module-compose-warn/index.html, packages/wmr/test/fixtures/css-module-compose-warn/index.js
=> Print file that triggered CSS compose warning

.changeset/dry-forks-yell.md, packages/wmr/src/plugins/process-global-plugin.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/process-complex/index.html, packages/wmr/test/fixtures/process-complex/index.js, packages/wmr/test/fixtures/process-complex/other.js
This fixes #818. The issue was happening because `code` is passed to MagicString, which assumes all offsets are relative to that string. However, `code` was being modified to prepend an import statement before it gets scanned by the regex, which caused all offsets for `.overwrite()` to be relative to the modified `code` instead of the one that was passed to MagicString.
=> Fix process.env import skewing env inlining offsets

.changeset/quiet-beers-deny.md, packages/preact-iso/router.js, packages/preact-iso/test/match.test.js
fix splat (/:x* and /:x+) matches being merged into props instead of params
=> [preact-iso] Router: pass splat matches in params prop instead of as props

packages/preact-iso/router.js
This fixes an odd behavior (not published yet) introduced in #831.
=> Fix wrong state when browser handles click event

packages/wmr/src/lib/plugins.js, packages/wmr/src/plugins/worker-plugin.js
HMR in transpiled iife (=non-module workers) seems to lead to incorrect AST output when it comes to `$IMPORT_META_HOT$`.
Spent a while debugging this and have not found the actual cause yet, so the changes here serve as a workaround to get them working again.
=> Disable HMR in iife workers

.changeset/gentle-phones-brush.md, packages/wmr/src/cli.js, packages/wmr/src/lib/normalize-options.js, packages/wmr/test/cli.test.js, packages/wmr/test/fixtures/cli-minify/index.html, packages/wmr/test/fixtures/cli-minify/index.js
=> Add `--minify` option to `build` command

.changeset/red-roses-divide.md, packages/wmr/src/lib/output-utils.js
=> Sort list of output files by size within a group

.changeset/chatty-dodos-flow.md, packages/wmr/src/plugins/worker-plugin.js, packages/wmr/test/fixtures/worker/foo.worker.js, packages/wmr/test/worker.test.js
It's harmless and only annoying.
=> Fix `iife` bundle warning in prod with non-module workers

.changeset/shiny-gifts-talk.md, packages/wmr/src/bundler.js, packages/wmr/src/lib/compile-single-module.js, packages/wmr/src/lib/npm-middleware.js, packages/wmr/src/lib/output-utils.js, packages/wmr/src/plugins/worker-plugin.js
Instead of just showing the warning message we'll now show where the warning came from and potentially display a code frame of the code if available.
Before:
After:
=> Improve CLI output for compilation warnings

.changeset/early-carrots-appear.md, packages/wmr/package.json, packages/wmr/src/build.js, packages/wmr/src/cli.js, packages/wmr/src/lib/output-utils.js, packages/wmr/src/plugins/less-plugin.js, packages/wmr/src/plugins/sass-plugin.js, packages/wmr/src/plugins/sucrase-plugin.js, packages/wmr/src/plugins/wmr/styles/styles-plugin.js, packages/wmr/test/fixtures/prerender-error/index.html, packages/wmr/test/fixtures/prerender-error/index.js, packages/wmr/test/production.test.js, yarn.lock
- 174e5f6 Fix weird code frame formatting if line is way longer than terminal width
- 1d9791f Add code frame to uncaught exceptions if possible
- 859be34 Mark prerender errors as such when logging to the terminal
Interestingly all uncaught exceptions from a worker land up in the handler on the main thread. This happens often on my end during prerendering when a variable is only available in the browser, but not in node.
Need to find a way to catch those in the worker or somehow annotate them as originating from prerendering. But for now the code frame alone makes it a lot easier to understand what's going on.
Before:
After:
=> Add code frame to uncaught exceptions if possible

packages/wmr/src/lib/fs-utils.js, packages/wmr/src/plugins/url-plugin.js
Convert windows paths to valid URL paths when inlining asset URLs
=> Fix inline asset paths on windows

.changeset/rare-moles-brush.md, packages/wmr/src/lib/normalize-options.js
Note: Didn't add a test as our test setup always enables debug by default to make inspection easier.
Fixes #855 .
=> Fix `debug: true` option in config file not being respected

.changeset/rude-goats-hammer.md, packages/wmr/package.json, packages/wmr/src/lib/acorn-default-plugins.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/class-fields-static/index.html, packages/wmr/test/fixtures/class-fields-static/index.js, yarn.lock
This code did throw an error due to the static class field:
```js
class Foo {
static state = 'class fields work';
}
```
This was already reported a while back in #708, but I didn't know that `acorn` needs a special plugin for static fields.
Fixes #708 .
=> Fix error when using static class fields

.changeset/short-pumas-eat.md, packages/wmr/src/plugins/process-global-plugin.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/process-present/foo.js, packages/wmr/test/fixtures/process-present/index.html, packages/wmr/test/fixtures/process-present/index.js
Resolve a wrongly replaced `process.env` variable when a binding with the name `process` is already in scope. This was encountered when bundling vscode's monaco-editor.
=> Fix false positive in process detection

.changeset/nice-snakes-press.md, packages/wmr/src/lib/output-utils.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/this-undefined/-node_modules/foo/index.js, packages/wmr/test/fixtures/this-undefined/-node_modules/foo/package.json, packages/wmr/test/fixtures/this-undefined/index.html, packages/wmr/test/fixtures/this-undefined/index.js, packages/wmr/test/test-helpers.js
It's harmless and mainly caused by polyfills of libraries in
`node_modules`. Rollup deals with that automatically. Came across this with `monaco-editor` where every file seemingly includes polyfills. This leads to the terminal being spammed constantly.
=> Don't flood terminal with Rollup's this is undefined warning

.changeset/great-drinks-obey.md, .changeset/tall-beers-lay.md, packages/preact-iso/router.d.ts, packages/preact-iso/router.js, packages/preact-iso/test/router.test.js
Fixes https://github.com/preactjs/wmr/issues/836
Ref solution: https://github.com/preactjs/wmr/pull/864/commits/d6c87e340538c341e7826b7b043dec03ddc306fd (ties into the effect on every render)
State solution: https://github.com/preactjs/wmr/pull/864/commits/960364758bd818d8c00a482ef4c346c7adc05554 (avoids using effect on every render)
=> (preact-iso) - avoid calling onLoadEnd on every render

docs/public/index.js
page.focus() needs to be called after all route changes, even if no loading occurred.
=> [docs] fix focus management

.changeset/rude-moons-grow.md, packages/preact-iso/router.js
I'm not 100% sure if this is the right solution, but reverting this line fixes the issue:
https://github.com/preactjs/wmr/pull/835/files#diff-b8c8c162d167c1ad31cb8461c49197c9c5527c58c2cde64d5c082d7359878ffdL123
My thinking is that `url` here is the full `location.path + location.search`, so the worst case is that we're potentially re-rendering routers that are unaffected by a given URL change.
=> [preact-iso] Fix Router un-rendering incoming same-component route

.changeset/young-carrots-relate.md, examples/demo/public/home.module.css, packages/wmr/src/wmr-middleware.js
Fixes #871
Format of files in `WRITE_CACHE`
```
{
'index.tsx',
'pages\\home\\index.js',
'home.module.css?asset',
'home.module.css',
'pages\\_404.js',
'header.tsx',
'pages\\home\\style.module.css?asset',
'pages\\home\\style.module.css'
}
```
While our `cacheKey` was in posix format, the `cacheKey` only seems to affect assets in this matter
=> (wmr) - fix issue relating to windows module css

.github/workflows/main.yml, packages/wmr/src/build.js, packages/wmr/src/plugins/wmr/styles/css-modules.js
This splits up the tests for preact-iso, wmr-dev and wmr-prod so we have a faster output across more machines.
If we merge this we'll have to tweak the mandatory status checks
CC @marvinhagemeister should we add 16.x to our matrix?
=> (chore) - speed up ci execution by seperating the steps

.changeset/honest-vans-float.md, .github/workflows/main.yml, examples/demo/package.json, examples/demo/public/foo/lib/test.ts, examples/demo/public/index.tsx, examples/demo/tsconfig.json, packages/wmr/package.json, packages/wmr/src/lib/plugins.js, packages/wmr/src/plugins/tsconfig-paths-plugin.js, yarn.lock
resolves https://github.com/preactjs/wmr/issues/740
=> (wmr) - support tsconfig-paths out of the box

.changeset/little-poets-mix.md, packages/wmr/rollup.config.js
Well it turns out they have a convenient env var for this.
Browserslist warning to update the `caniuse-lite` db isn't actionable to end users due to it being bundled.
=> chore: Disables (non-actionable) browserslist warning for users

.changeset/pink-turtles-switch.md, packages/wmr/src/lib/prerender.js
The first script tag in the file _should_ be assumed to have a `prerender()`, however, due to the loop continuing even after the first non-external script tag is found, it was actually the _last_ script tag that was used and would need to have `prerender()`.
It should be noted that [this behavior has existed for the past 9 months](https://github.com/preactjs/wmr/commit/ba2e29f2d5b3fb1a91301c1bff4f2dfba37fb335), and fixing it could potentially cause someone's setup to break. We could just flip the error message/comments instead?
https://github.com/preactjs/wmr/blob/039f79925ecab2e277d32e1f4f7341d38a222b59/packages/wmr/src/lib/prerender.js#L106
=> fix: Last, not first, non-external script in HTML should have prerender()

.changeset/six-pandas-look.md, packages/wmr/src/lib/prerender.js, packages/wmr/test/fixtures/prerender-data/index.js
Fixes #912 
Switch from token based replacement to callback based function to avoid replacement of `$1` form within html and data contents at prerender time.
=> (fix) Avoid replacing regex group token when present in html

.changeset/strong-rabbits-juggle.md, packages/wmr/src/lib/acorn-traverse.js
Supports TLA in dev. Users would otherwise be me with the following:
> 500 \<source\> - Cannot use keyword 'await' outside an async function (\<source\>)
I should add that TLA works just fine in prod build; parser doesn't throw an error and allows it to pass just fine. This is only an issue in dev.
This of course won't work in all environments, but I think it's probably fair to at least enable the syntax to get past the parser? If a user needs to support an older browser or is running a version of Node that doesn't support it, I think it's fair to leave that up to them to correct.
=> feat: Allow top-level await in dev

.github/workflows/main.yml, .github/workflows/release.yml
Changed the version of Node.js used for testing and releases.
Version 18 is not yet LTS, but is being added because we want to test using version 18 at https://github.com/preactjs/wmr/pull/935 (and Node.js version 18 will be LTS in the near future)
I am a bit fearful that this change will break existing mechanisms and workflows, but I will watch CI on this branch and make modifications as appropriate.
=> Fix Node.js version of GitHub Actions workflow

.changeset/young-guests-tap.md, packages/wmr/src/lib/prerender.js, packages/wmr/test/fixtures/prerender-external-resource-fetch/index.html, packages/wmr/test/fixtures/prerender-external-resource-fetch/index.js, packages/wmr/test/fixtures/prerender-resource-fetch/index.js, packages/wmr/test/production.test.js
I've defined globalThis.fetch at https://github.com/preactjs/wmr/pull/934, but currently wmr can't access external resources when use prerender mode.
Therefore, I came up with a plan to make fetch available natively in Node.js 18 and later.
But Node.js 18 is not LTS yet, what do you think?
=> Feat proposal enable fetching external resources using native fetch API in Node.js version 18 later

.changeset/lemon-doors-hunt.md, packages/wmr/src/lib/sourcemap.js
Closes #926 
[Per the spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?pli=1), `sourcesContent` is optional so we need to check for its existence before consuming.
=> fix: Ensure sourcemap `sourcesContent` exists before trying to consume

.changeset/thick-apes-relax.md, packages/create-wmr/src/index.js
I noticed while using `create-wmr` that when passing `--eslint`, `eslint` and `eslint-config-preact` ended up in `"dependencies"` instead of `"devDependencies"` in my `package.json`.
- I added eslint-disable comments because the commit hook was blocking me from committing the file with the pre-existing console statements in it. I saw disable comments in other packages so I figured that's appropriate.
- I haven't been able to manually validate this. Running `yarn prepare` in the `create-wmr` package directory hangs and uses up a whole lot of my CPU. And I'm unable to directly execute `src/index.js` as it uses ES module syntax. Telling node that it's a module results in `__dirname is not defined` errors, as `__dirname` isn't available in ES modules' scope.
=> create-wmr: install eslint and eslint-config-preact as dev dependencies

.changeset/moody-shirts-smash.md, packages/wmr/src/plugins/worker-plugin.js
Workers must have [`.worker` in their name](https://github.com/preactjs/wmr/blob/ab4b512875ae63273cfbd9c4c5972aadd3218bac/packages/wmr/src/plugins/worker-plugin.js#L23) yet this regex didn't test for it. So `new URL('./foo.js', import.meta.url)` is (incorrectly) treated as a worker.
This behavior is still super sketchy and flawed, as a simple `console.log(new URL('./foo.worker.js', import.meta.url))` will trigger (in prod, in dev the user will just get errors) WMR to emit another file, but this at least reduces the chances of users running into it.
=> fix: Worker detection
