preactjs/wmr

src/serve.js
Follow up to #204 since that PR forgot to touch the code for serve
=> Move server address log to listen callback for serve

packages/preact-iso/package.json
So that you get a nice link to the repository from the npm package page.
=> chore: add repository field to preact-iso package.json

package.json, src/plugins/fast-cjs-plugin.js, src/plugins/wmr/plugin.js
Fixes: https://github.com/preactjs/wmr/issues/182
=> fix hmr for modules not referencing module.hot

README.md
Closes https://github.com/preactjs/wmr/issues/183
=> add html minification recipe

package-lock.json, package.json
Ran npm audit which upgraded some deps
=> Run npm audit

src/lib/npm-middleware.js
=> fix: Aliases on npm modules

README.md
I accidentely did the Preact one 😅
=> Fix wrong npm badge

src/lib/transform-jsx-to-htm-lite.js, src/plugins/htm-plugin.js, test/acorn-traverse.test.js, test/fixtures/_unit/jsx-nesting.expected.js, test/fixtures/transformations/jsx-escaped.expected.js, test/fixtures/transformations/jsx-member.expected.js, test/fixtures/transformations/jsx.expected.js
=> Use $$html for transpiled JSX

src/wmr-middleware.js
Fixes https://github.com/preactjs/wmr/issues/246
=> normalize paths for windows nested hmr

packages/preact-iso/index.js
Just a quick addendum to #274.
=> [preact-iso] Re-export useLocation

packages/preact-iso/lazy.js
=> [preact-iso] Make lazy() thrown promise resolve to component

src/plugins/wmr/client.js
Not all inserted stylesheets will have a url, think about css-in-js, ...
=> Fix case where a stylesheet wouldn't reload

src/plugins/process-global-plugin.js
webpack provides this, some libraries use it to detect browser usage
=> feat: add `process.browser` for compatibility

src/cli.js, src/lib/normalize-options.js, src/plugins/wmr/plugin.js, src/wmr-middleware.js, types.d.ts
This seperates wmr further away from Preact
=> make prefresh optional

src/plugins/fast-cjs-plugin.js
=> Tighten up ESM_KEYWORDS

src/lib/transform-jsx-to-htm-lite.js, test/fixtures/transformations/jsx-self-closed.expected.js, test/fixtures/transformations/jsx-self-closed.js, test/transformations.test.js
=> Fix wrong output for self closed non-root jsx nodes

packages/wmr/test/bench/jsx.js
```sh
npm i benchmarkjs-pretty
node test/bench/jsx.js
```
=> Add JSX transforms benchmark

packages/preact-iso/lazy.js, packages/preact-iso/package.json, packages/preact-iso/router.js, packages/preact-iso/test/router.test.js, yarn.lock
Some crazy stuff in here, but it does work.
h/t to @cristianbote for most of the work.
=> Route flicker 2

README.md
=> docs: Fixing a few broken links after monorepo refactor

.changeset/warm-dragons-wonder.md, packages/wmr/src/wmr-middleware.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/hmr/home.js, packages/wmr/test/fixtures/hmr/useCounter.js
Fixes https://github.com/preactjs/wmr/issues/386
=> (wmr) - convert dependents set to array

.changeset/dirty-geese-heal.md, packages/wmr/src/lib/prerender.js, packages/wmr/test/fixtures/prod-routes/_404.js, packages/wmr/test/fixtures/prod-routes/about.js, packages/wmr/test/fixtures/prod-routes/header.js, packages/wmr/test/fixtures/prod-routes/index.html, packages/wmr/test/fixtures/prod-routes/index.js, packages/wmr/test/production.test.js
Fixes https://github.com/preactjs/wmr/issues/392
=> (wmr) - remove search in prerender

.changeset/green-camels-drop.md, packages/wmr/src/plugins/wmr/styles-plugin.js
=> (wmr) Fix source maps in styles-plugin

.changeset/green-camels-drop.md, .changeset/silver-chicken-travel.md, packages/wmr/src/cli.js, packages/wmr/src/plugins/wmr/styles-plugin.js
=> (wmr) Move sourcemap option from start to build command

packages/preact-iso/README.md
This is reflecting changes of #359 in documentation
=> (preact-iso) Switch from useLoc to useLocation

.changeset/curvy-suns-explain.md, packages/preact-iso/router.d.ts
=> (preact-iso) Add type definitions to router onLoadEnd and onLoadStart callbacks

.changeset/hip-peaches-jam.md, packages/preact-iso/lazy.d.ts
=> Add missing `onError` type for ErrorBoundary

.changeset/lucky-suits-worry.md, packages/wmr/demo/public/index.tsx, packages/wmr/src/plugins/wmr/client.js, packages/wmr/src/start.js, packages/wmr/src/wmr-middleware.js
=> (wmr) - report js-build errors to the client

packages/wmr/src/plugins/wmr/client.js
=> revert to int timestamps

.changeset/wise-llamas-exist.md, packages/wmr/src/lib/normalize-options.js
Credits to @danielweck for spotting this!
=> Don't resolve config file twice

packages/wmr/types.d.ts
Thanks to @danielweck for spotting this!
Fixes #443
=> Add missing wildcard to import prefix types

packages/wmr/src/plugins/wmr/styles-plugin.js
Fixes https://github.com/preactjs/wmr/issues/439
=> Ensure we cant duplicate fields in the set

.changeset/rare-rules-draw.md, packages/directory-plugin/types.d.ts, packages/sw-plugin/types.d.ts
Resolves https://github.com/preactjs/wmr/issues/451
=> (sw/dir) - add missing import prefix types

.changeset/big-games-refuse.md, packages/wmr/src/bundler.js, packages/wmr/src/global.d.ts, packages/wmr/src/lib/normalize-options.js, packages/wmr/src/wmr-middleware.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/plugin-enforce/public/index.html, packages/wmr/test/fixtures/plugin-enforce/public/scripts.js, packages/wmr/test/fixtures/plugin-enforce/wmr.config.mjs, packages/wmr/test/fixtures/plugin-middlewares/public/index.html, packages/wmr/test/fixtures/plugin-middlewares/wmr.config.mjs, packages/wmr/types.d.ts
This PR adds support for returning plugins or an array of plugins from our configuration file.
=> Improve plugin API

.changeset/small-islands-clean.md, packages/preact-iso/router.js, packages/sw-plugin/src/index.js, packages/wmr/src/lib/environment.js
=> Fix Eslint and Prettier suggestions

.changeset/blue-trains-drum.md, packages/wmr/src/start.js
We already do that in `normalizeOptions` now since #470
=> Only search for free port once

packages/wmr/test/fixtures/dynamic-import/index.js
This reduces flakyness of a test.
=> Guard against race condition in test assertion

.gitignore, examples/demo/package.json, yarn.lock
=> Add local Lighthouse CI script

.changeset/poor-vans-kiss.md, packages/wmr/package.json, packages/wmr/src/lib/acorn-traverse.js, packages/wmr/src/lib/output-utils.js, packages/wmr/src/plugins/sucrase-plugin.js, packages/wmr/src/plugins/wmr/client.js, packages/wmr/src/server.js, packages/wmr/src/start.js, packages/wmr/src/wmr-middleware.js, yarn.lock
Before:
After:
---
Before:
After:
Fixes #514 .
=> Unify error logging to console

.changeset/tasty-onions-walk.md, packages/wmr/src/lib/output-utils.js, packages/wmr/src/lib/rollup-plugin-container.js, packages/wmr/src/plugins/npm-plugin/index.js, packages/wmr/src/wmr-middleware.js
This is currently a lifesaver for me as it makes debugging resolution logic a lot easier
=> Add more resolution debug logs

.changeset/tasty-kids-breathe.md, packages/directory-plugin/package.json, packages/nomodule-plugin/index.js, packages/nomodule-plugin/package.json, packages/sw-plugin/package.json
See #494 for more information. The migration will be done in steps to ensure a smooth user experience.
=> Move packages to @wmrjs org

packages/preact-iso/router.js
This fixes a regression introduced in #504:
https://github.com/preactjs/wmr/pull/504/files#diff-b8c8c162d167c1ad31cb8461c49197c9c5527c58c2cde64d5c082d7359878ffdR126
=> [preact-iso] Bugfix for swapping suspended routes

.changeset/large-scissors-shave.md, packages/wmr/src/lib/output-utils.js
=> Add startup note on network access

README.md, docs/package.json, packages/directory-plugin/README.md, packages/nomodule-plugin/README.md, packages/sw-plugin/README.md, yarn.lock
=> Rename @wmr-plugins -> @wmrjs

packages/wmr/package.json, packages/wmr/tools/run-fixture.js
Usage: `yarn wmr fixture <fixture>`
=> Add "fixture" script for easier fixture debugging

.changeset/tricky-scissors-grab.md, packages/wmr/src/plugins/process-global-plugin.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/import-meta-env/index.html, packages/wmr/test/fixtures/import-meta-env/index.js, packages/wmr/test/production.test.js, packages/wmr/types.d.ts
=> Add support for loading env variables from `import.meta.env`

.changeset/famous-scissors-buy.md, packages/wmr/src/lib/prerender.js, packages/wmr/test/fixtures/prerender-external/index.html, packages/wmr/test/fixtures/prerender-external/index.js, packages/wmr/test/production.test.js
=> Don't attempt to prerender external URLs

.changeset/curvy-dodos-marry.md, packages/create-wmr/src/index.js, packages/create-wmr/tpl/package.json
Still need to find a better way of dealing with these
Figured I'd touch up the `wmr` version while I was at it, but only `preact-iso` needed a fix
=> chore: Updating template deps

.changeset/chatty-beds-applaud.md, docs/public/content/docs/index.md, docs/public/prerender.js, examples/demo/public/header.tsx, examples/demo/public/index.tsx, packages/create-wmr/tpl/public/header.js, packages/create-wmr/tpl/public/index.js, packages/directory-plugin/example/public/index.js, packages/preact-iso/README.md, packages/wmr/README.md, packages/wmr/test/fixtures/prod-routes/index.js
As discussed in slack. Only added a changeset for `create-wmr` as all other packages only have README changes or changes in their example app.
=> Switch from subpackage to main imports for `preact-iso`

.changeset/light-cows-obey.md, packages/wmr/package.json, packages/wmr/test/transformations.test.js, yarn.lock
Fix is in this commit on the stylis repo https://github.com/thysultan/stylis.js/commit/50ed71a7746b9965337f7811767f23eefcab6fe9
=> Fix deeply nested CSS class not being hashed

.github/workflows/compressed-size.yml, package.json, packages/preact-iso/package.json, packages/preact-iso/test/bundle-using-wmr.js
(trying to get both individual and combined sizes reported)
=> Run compressed-size-action on preact-iso PRs

.changeset/mean-spoons-melt.md, packages/wmr/src/lib/prerender.js, packages/wmr/test/production.test.js
Reverts preactjs/wmr#591
Looks like want to experiment with variants of this and alternative approaches before we settle on one
=> Revert "write prerender data to json file"

packages/wmr/src/start.js
`server` is a value here and needs to be converted to a type to be able to check it
=> Fix invalid TS signature

.changeset/chilly-owls-relate.md, packages/wmr/src/lib/acorn-traverse.js, packages/wmr/test/acorn-traverse.test.js
=> Fix missing whitespace when JSXText spans multiple lines

.changeset/dry-feet-pretend.md, packages/wmr/src/lib/normalize-options.js, packages/wmr/test/fixtures.test.js
Fixes a regression that was introduced with #631  .
=> Fix temporary config file not deleted with TS

.changeset/forty-suns-impress.md, examples/demo/wmr.config.js, packages/wmr/src/lib/acorn-traverse.js, packages/wmr/test/acorn-traverse.test.js
Fixes #632 and builds on top of #622
=> Adapt the newline regex rule to match any char range

.changeset/fast-peaches-impress.md, packages/wmr/src/lib/acorn-traverse.js, packages/wmr/test/acorn-traverse.test.js
=> Fix unable to code generate JSXMemberExpression and JSXEmptyExpression nodes

.changeset/purple-ties-sing.md, packages/wmr/src/plugins/wmr/styles-plugin.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/css-module-reserved/foo.module.css, packages/wmr/test/fixtures/css-module-reserved/index.html, packages/wmr/test/fixtures/css-module-reserved/index.js
=> Fix CSS Modules mappings containing invalid identifiers

package.json, packages/wmr/package.json, packages/wmr/src/lib/normalize-options.js, packages/wmr/src/lib/npm-middleware.js, packages/wmr/src/lib/output-utils.js, packages/wmr/src/lib/rollup-plugin-container.js, packages/wmr/src/lib/transform-css.js, packages/wmr/src/lib/~publish.js, packages/wmr/src/plugins/npm-plugin/size-warning-plugin.js, packages/wmr/src/plugins/optimize-graph-plugin.js, packages/wmr/src/plugins/sass-plugin.js, packages/wmr/src/plugins/wmr/client.js, packages/wmr/src/start.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/production.test.js, packages/wmr/test/test-helpers.js
Remove leftover logging statement and ensure that our linter catches those
=> Enable no-console rule

docs/public/components/header.js, docs/public/content/docs/prerendering.md, docs/public/styles/index.css
See commits for individual list of changes.
=> Docs: Minor design updates + prerender page

docs/public/components/doc-structure.js
This fixes a regression introduced with 9ee653794637de25491be7c8e4e5749102e00fdc
=> Docs: Fix missing pagination

docs/public/components/doc-structure.js
Fixes another regression introduced with 9ee653794637de25491be7c8e4e5749102e00fdc
=> Docs: Fix wrong pagination with headings

.changeset/chatty-clouds-watch.md, packages/wmr/src/lib/default-loaders.js, packages/wmr/src/plugins/process-global-plugin.js
Each plugin should only work on files it can understand
=> Update plugin file checks

docs/plugins/markdown.js
Minor regression introduced with #680 . Forgot to update the paths in the plugins for the docs page.
=> Docs: Fix markdown rendering

.changeset/fresh-hounds-tease.md, packages/create-wmr/tpl/public/index.html
=> Use <link rel=modulepreload>

.changeset/hot-apricots-perform.md, packages/wmr/package.json, yarn.lock
See: https://github.com/marvinhagemeister/kolorist/pull/9
=> Fix missing colors in CI environments

.changeset/popular-moons-kneel.md, packages/wmr/package.json, packages/wmr/rollup.config.js, packages/wmr/src/cli.js, yarn.lock
=> Fix missing version on --version

.changeset/tame-buttons-double.md, docs/public/content/docs/configuration.md, packages/wmr/src/lib/normalize-options.js, packages/wmr/src/lib/prerender.js, packages/wmr/test/fixtures/prerender-additional-links/wmr.config.mjs, packages/wmr/types.d.ts
=> Rename prerenderLinks to customRoutes

.changeset/beige-turtles-heal.md, packages/wmr/src/lib/net-utils.js, packages/wmr/src/plugins/wmr/client.js, packages/wmr/src/wmr-middleware.js, packages/wmr/test/css.test.js, packages/wmr/test/fixtures/css-module-hmr/index.html, packages/wmr/test/fixtures/css-module-hmr/index.js
=> Fix HMR updates not bubbled through proxy modules

.changeset/rotten-dragons-fetch.md, packages/wmr/src/plugins/html-entries-plugin.js, packages/wmr/test/fixtures/base64-html/public/index.html, packages/wmr/test/production.test.js
~~This should fix #749.~~
Fixes #749 .
=> Preserve Data URLs in script tags

.changeset/twelve-flowers-sniff.md, packages/wmr/src/plugins/sass-plugin.js, packages/wmr/test/fixtures.test.js
=> Sass: Fix "missing compiler" error not shown to the user

packages/wmr/src/lib/acorn-traverse.js, packages/wmr/test/acorn-traverse.test.js
This PR adds various methods that the babel prefresh plugin relies upon.
=> Acorn: Improve babel compat

.changeset/yellow-cars-tie.md, packages/wmr/src/lib/plugins.js, packages/wmr/src/plugins/absolute-path-plugin.js, packages/wmr/src/plugins/sass-plugin.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/css-sass-absolute/bar.scss, packages/wmr/test/fixtures/css-sass-absolute/foo.scss, packages/wmr/test/fixtures/css-sass-absolute/index.html
=> Fix absolute root-relative imports not working

.changeset/wet-birds-sip.md, packages/wmr/src/lib/plugins.js, packages/wmr/src/plugins/copy-assets-plugin.js, packages/wmr/src/plugins/html-entries-plugin.js, packages/wmr/src/plugins/sass-plugin.js, packages/wmr/test/fixtures/css-sass-import-hash-html/public/2.scss, packages/wmr/test/fixtures/css-sass-import-hash-html/public/index.html, packages/wmr/test/fixtures/css-sass-import-hash-html/public/style.scss, packages/wmr/test/fixtures/css-sass-import-hash/public/2.scss, packages/wmr/test/fixtures/css-sass-import-hash/public/index.html, packages/wmr/test/fixtures/css-sass-import-hash/public/index.js, packages/wmr/test/fixtures/css-sass-import-hash/public/style.scss, packages/wmr/test/production.test.js
Fixes https://github.com/preactjs/wmr/issues/772
Fixes https://github.com/preactjs/wmr/issues/361
=> several sass fixes

.changeset/brave-toys-learn.md, packages/wmr/src/plugins/wmr/client.js
The HMR client works in a Module Worker context, it was just trying to check for stylesheets and construct DOM trees.
=> Fix HMR breaking in Web Workers

packages/wmr/package.json, packages/wmr/src/plugins/copy-assets-plugin.js, packages/wmr/src/plugins/html-entries-plugin.js, packages/wmr/src/plugins/sass-plugin.js, yarn.lock
Wasn't able to build wmr on a fresh clone.
=> Add missing mime dependency

.changeset/thin-impalas-hear.md, packages/wmr/src/lib/rollup-plugin-container.js, packages/wmr/src/wmr-middleware.js, packages/wmr/test/fixtures.test.js, packages/wmr/test/fixtures/watch/public/foo.js, packages/wmr/test/fixtures/watch/public/index.html, packages/wmr/test/fixtures/watch/public/index.js, packages/wmr/test/fixtures/watch/wmr.config.mjs
=> Fix missing watch events in rollup plugins

packages/wmr/src/lib/transform-jsx-to-htm-lite.js, packages/wmr/test/fixtures/transformations/jsx-comment-2.expected.js, packages/wmr/test/fixtures/transformations/jsx-comment-2.js, packages/wmr/test/fixtures/transformations/jsx-comment.js, packages/wmr/test/transformations.test.js
=> Work around JSX transform double comment replacement

.changeset/mean-trainers-join.md, packages/wmr/src/serve.js, packages/wmr/src/start.js
For some reason they were flipped.
=> Distinguish dev server vs serve command in output

.changeset/swift-bobcats-try.md, packages/wmr/package.json, packages/wmr/src/lib/~publish.js
Thanks to @rschristian for finding the actual cause of #845 👍 
Fixes #845 .
=> Fix missing `description` and `license` field in published wmr `package.json`

.changeset/grumpy-olives-call.md, packages/wmr/src/lib/normalize-options.js, packages/wmr/test/fixtures/plugin-config-falsy/public/index.html, packages/wmr/test/fixtures/plugin-config-falsy/wmr.config.mjs, packages/wmr/test/plugins/plugins.test.js
=> Filter out falsy values in `plugins` and `middleware` array in config

packages/wmr/tools/run-fixture.js
Adds command parameter and copies local modules in the test case.
=> Improve fixture script

packages/wmr/tools/run-fixture.js
Follow up to #865 which I merged too early 👀
=> Fix run-fixture fake node_modules logic

.changeset/twenty-bikes-pull.md, packages/wmr/src/cli.js
...(default: true) (default true)
=> docs: Remove duplicate info in CLI help menu
